services:
  - type: web
    name: online-notes-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn online_notes.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: online_notes.settings
      - key: SECRET_KEY
        fromSecret: django-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: online-notes-db
          property: connectionString
      - key: DEBUG
        value: "False"
        envVars:
  - key: ALLOWED_HOSTS
    value: "online-notes-app.onrender.com"


databases:
  - name: online-notes-db
    region: oregon
    plan: free
